import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark w-screen flex`}
      >
        <div className="flex flex-col w-full gap-2">

          <div className="flex gap-4 w-full items-center justify-center">

            <Link href='/' className="p-2 bg-secondary rounded" >Home</Link>
            <Link href='/protected' className="p-2 bg-secondary rounded" >Protected</Link>
            <Link href='/admin' className="p-2 bg-secondary rounded" >Admin</Link>
            <Link href='/auth' className="p-2 bg-secondary rounded" >Auth</Link>
          </div>

          {children}

        </div>
      </body>
    </html>
  );
}
